version: "3.0"
services:

  db:
    image: "postgres:9.4"
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - result-tier
      - back-tier

  poll:
    build: poll
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    depends_on:
      - redis
    networks:
      - poll-tier

  redis:
    image: "redis:6.0"
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: worker
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    depends_on:
      - db
      - redis
    networks:
      - back-tier

  result:
    build: result
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - result-tier

networks:
  poll-tier:
  back-tier:
  result-tier:

volumes:
  db-data:
