##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## Makefile
##

NAME	=	infin_add

all:		$(NAME)

$(NAME):
	gcc -o infin_add lib/my/*.c *.c

clean:
	rm -f infin_add

fclean: 	clean
	rm -f $(NAME)

re:			fclean all
